# Generated by Django 6.0.4 on 2026-05-13 16:37

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_credit_card_statement_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(models.F('user'), django.db.models.functions.text.Lower('name'), name='unique_account_name_ci_per_user'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(models.F('user'), models.F('category_type'), django.db.models.functions.text.Lower('name'), name='unique_category_name_ci_per_user_type'),
        ),
    ]
