# Generated by Django 6.0.4 on 2026-05-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_account_unique_account_name_ci_per_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringpayment',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Gasto')], default='expense', max_length=24),
        ),
    ]
