# Generated by Django 6.0.4 on 2026-06-15 00:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0007_add_recurring_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['user', '-date'], name='finanzas_fi_user_id_21f8e9_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['user', 'status'], name='finanzas_fi_user_id_93cd4d_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringpayment',
            index=models.Index(fields=['user', 'is_subscription', 'next_due_date'], name='finanzas_re_user_id_d79b35_idx'),
        ),
    ]
