# Generated by Django 6.0.7 on 2026-07-31 22:48

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def initialize_security_and_catalog_state(apps, schema_editor):
    SetupState = apps.get_model('finanzas', 'SetupState')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    RecurringPayment = apps.get_model('finanzas', 'RecurringPayment')
    FinancialTransaction = apps.get_model('finanzas', 'FinancialTransaction')

    SetupState.objects.create(consumed_at=timezone.now() if User.objects.exists() else None)
    insurance_names = [
        'Seguro de auto privado',
        'Seguro de vida privado',
        'Seguro de salud privado',
        'Seguro de ingreso',
    ]
    RecurringPayment.objects.filter(is_subscription=True, name__in=insurance_names).update(
        subscription_catalog='insurance'
    )

    # Preserve the earliest generated occurrence and void legacy duplicates
    # before the database uniqueness constraint becomes authoritative.
    seen = set()
    rows = FinancialTransaction.objects.filter(source_recurring_id__isnull=False).exclude(
        status='void'
    ).order_by('id')
    for row in rows.iterator():
        key = (row.source_recurring_id, row.date)
        if key in seen:
            row.status = 'void'
            row.save(update_fields=['status'])
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0008_alter_account_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_hash', models.CharField(max_length=64)),
                ('identity_hash', models.CharField(max_length=64)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SetupState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='recurringpayment',
            name='subscription_catalog',
            field=models.CharField(choices=[('service', 'Servicio'), ('insurance', 'Seguro')], default='service', max_length=16),
        ),
        migrations.RunPython(initialize_security_and_catalog_state, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_limit__isnull', True), ('monthly_limit__gt', 0), _connector='OR'), name='category_monthly_limit_positive'),
        ),
        migrations.AddConstraint(
            model_name='creditcard',
            constraint=models.CheckConstraint(condition=models.Q(('credit_limit__gt', 0)), name='credit_card_limit_positive'),
        ),
        migrations.AddConstraint(
            model_name='creditcard',
            constraint=models.CheckConstraint(condition=models.Q(('current_debt__gte', 0)), name='credit_card_debt_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='creditcard',
            constraint=models.CheckConstraint(condition=models.Q(('annual_interest_rate__gte', 0)), name='credit_card_interest_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='creditcard',
            constraint=models.CheckConstraint(condition=models.Q(('statement_day__gte', 1), ('statement_day__lte', 31)), name='credit_card_statement_day_range'),
        ),
        migrations.AddConstraint(
            model_name='creditcard',
            constraint=models.CheckConstraint(condition=models.Q(('payment_due_day__gte', 1), ('payment_due_day__lte', 31)), name='credit_card_due_day_range'),
        ),
        migrations.AddConstraint(
            model_name='financialtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transaction_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='financialtransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('source_recurring__isnull', False), models.Q(('status', 'void'), _negated=True)), fields=('source_recurring', 'date'), name='unique_active_recurring_occurrence'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gt', 0)), name='invoice_subtotal_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('tax__gte', 0)), name='invoice_tax_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('credit', 0), ('debit__gt', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='journal_line_exactly_one_side'),
        ),
        migrations.AddConstraint(
            model_name='recurringpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='recurring_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='loginthrottle',
            index=models.Index(fields=['locked_until'], name='finanzas_lo_locked__6cf6b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='loginthrottle',
            constraint=models.UniqueConstraint(fields=('network_hash', 'identity_hash'), name='unique_login_throttle_identity_network'),
        ),
    ]
