# Generated by Django 6.0.8 on 2026-09-08 18:24

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0009_loginthrottle_setupstate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='Origin of the import (gmail, csv, chatgpt, etc.)', max_length=50)),
                ('external_batch_id', models.CharField(blank=True, help_text='External identifier for idempotency', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional source-specific data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('external_id', models.CharField(help_text='External identifier for deduplication', max_length=100)),
                ('merchant', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('transaction_date', models.DateField(default=django.utils.timezone.localdate)),
                ('transaction_type', models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Gasto'), ('transfer', 'Transferencia'), ('card_payment', 'Pago de tarjeta'), ('collection', 'Cobro')], max_length=24)),
                ('confidence', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Confidence score 0.00-1.00 from AI/import', max_digits=5)),
                ('fingerprint', models.CharField(blank=True, help_text='SHA256 fingerprint for fuzzy deduplication', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('duplicate', 'Duplicado'), ('error', 'Error')], default='pending', max_length=20)),
                ('raw_metadata', models.JSONField(blank=True, default=dict, help_text='Raw source data for audit/debug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drafts_as_account', to='finanzas.account')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='finanzas.importbatch')),
                ('destination_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drafts_as_destination', to='finanzas.account')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_drafts', to=settings.AUTH_USER_MODEL)),
                ('suggested_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_drafts', to='finanzas.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('external_batch_id__gt', '')), fields=('user', 'external_batch_id'), name='unique_import_batch_per_user_source'),
        ),
        migrations.AddConstraint(
            model_name='transactiondraft',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('user', 'source', 'external_id'), name='unique_draft_external_id'),
        ),
        migrations.AddConstraint(
            model_name='transactiondraft',
            constraint=models.UniqueConstraint(condition=models.Q(('fingerprint__gt', '')), fields=('user', 'fingerprint'), name='unique_draft_fingerprint'),
        ),
    ]
