# Generated by Django 6.0.8 on 2026-09-08 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0010_importbatch_transactiondraft_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for this token', max_length=100)),
                ('token_hash', models.CharField(help_text='SHA256 hash of the token', max_length=64)),
                ('token_prefix', models.CharField(help_text='First 8 characters for identification', max_length=8)),
                ('scopes', models.JSONField(default=list, help_text='List of granted scopes')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MCPAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(max_length=100)),
                ('scope', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('result', models.CharField(choices=[('success', 'Éxito'), ('failure', 'Fallo'), ('denied', 'Denegado'), ('error', 'Error')], max_length=10)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('object_reference', models.CharField(blank=True, max_length=100)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='finanzas.mcpaccesstoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='mcpaccesstoken',
            index=models.Index(fields=['user', 'enabled'], name='finanzas_mc_user_id_dbefc2_idx'),
        ),
        migrations.AddIndex(
            model_name='mcpaccesstoken',
            index=models.Index(fields=['token_hash'], name='finanzas_mc_token_h_80fda6_idx'),
        ),
        migrations.AddIndex(
            model_name='mcpauditevent',
            index=models.Index(fields=['user', '-timestamp'], name='finanzas_mc_user_id_64cf07_idx'),
        ),
        migrations.AddIndex(
            model_name='mcpauditevent',
            index=models.Index(fields=['token', '-timestamp'], name='finanzas_mc_token_i_be13d1_idx'),
        ),
        migrations.AddIndex(
            model_name='mcpauditevent',
            index=models.Index(fields=['tool', '-timestamp'], name='finanzas_mc_tool_86a85b_idx'),
        ),
    ]
