# Generated by Django 6.0.8 on 2026-09-09 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0011_mcpaccesstoken_mcpauditevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='importbatch',
            name='unique_import_batch_per_user_source',
        ),
        migrations.RemoveConstraint(
            model_name='transactiondraft',
            name='unique_draft_fingerprint',
        ),
        migrations.RemoveIndex(
            model_name='mcpaccesstoken',
            name='finanzas_mc_token_h_80fda6_idx',
        ),
        migrations.AddField(
            model_name='mcpaccesstoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mcpauditevent',
            name='token_identifier',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='mcpauditevent',
            name='transport',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='transactiondraft',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='finanzas.transactiondraft'),
        ),
        migrations.AddField(
            model_name='transactiondraft',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_draft', to='finanzas.financialtransaction'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='source',
            field=models.CharField(help_text='Origin of the import (gmail, csv, chatgpt, ...)', max_length=50),
        ),
        migrations.AlterField(
            model_name='mcpaccesstoken',
            name='name',
            field=models.CharField(help_text='Nombre legible del token', max_length=100),
        ),
        migrations.AlterField(
            model_name='mcpaccesstoken',
            name='scopes',
            field=models.JSONField(default=list, help_text='Lista de scopes concedidos'),
        ),
        migrations.AlterField(
            model_name='mcpaccesstoken',
            name='token_hash',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='mcpaccesstoken',
            name='token_prefix',
            field=models.CharField(editable=False, max_length=8),
        ),
        migrations.AlterField(
            model_name='mcpauditevent',
            name='result',
            field=models.CharField(choices=[('success', 'Exito'), ('failure', 'Fallo'), ('denied', 'Denegado'), ('error', 'Error')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mcpauditevent',
            name='user_agent',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='transactiondraft',
            name='external_id',
            field=models.CharField(blank=True, help_text='External identifier for exact deduplication (normalized)', max_length=100),
        ),
        migrations.AlterField(
            model_name='transactiondraft',
            name='raw_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Sanitized raw source data for audit/debug'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['user', 'source'], name='finanzas_im_user_id_14a4cb_idx'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['user', 'status'], name='finanzas_im_user_id_398f0c_idx'),
        ),
        migrations.AddIndex(
            model_name='mcpaccesstoken',
            index=models.Index(fields=['token_prefix'], name='finanzas_mc_token_p_582b93_idx'),
        ),
        migrations.AddIndex(
            model_name='transactiondraft',
            index=models.Index(fields=['user', 'status'], name='finanzas_tr_user_id_9047ea_idx'),
        ),
        migrations.AddIndex(
            model_name='transactiondraft',
            index=models.Index(fields=['user', 'source'], name='finanzas_tr_user_id_12b300_idx'),
        ),
        migrations.AddIndex(
            model_name='transactiondraft',
            index=models.Index(fields=['batch'], name='finanzas_tr_batch_i_a878ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('external_batch_id__gt', '')), fields=('user', 'source', 'external_batch_id'), name='unique_import_batch_per_user_source'),
        ),
        migrations.AddConstraint(
            model_name='transactiondraft',
            constraint=models.UniqueConstraint(condition=models.Q(('fingerprint__gt', ''), ('status', 'pending')), fields=('user', 'fingerprint'), name='unique_draft_fingerprint'),
        ),
    ]
