# Generated by Django 6.0.8 on 2026-09-09 18:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0012_remove_importbatch_unique_import_batch_per_user_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transactiondraft',
            name='unique_draft_external_id',
        ),
        migrations.AddConstraint(
            model_name='transactiondraft',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__gt', ''), ('status', 'pending')), fields=('user', 'source', 'external_id'), name='unique_draft_external_id'),
        ),
    ]
